### PR TITLE
Improve rom

### PR DESCRIPTION
**Pull request by ItsVixano**
100 fps on pabge, now on an 20$ phone on wish

### CODE REVIEW

**Comment by sashascurtu** [comment]
@spkal01 pls merg

**Comment by spkal01** [comment]
Lol

**Comment by NitroFuN** [comment]
Pro improvements

**Comment by ItsVixano** [comment]
> Lol

bro xiaomi did a mess during 1955 - 1975 period bro pls merge :pray: :pray: :pray: :pray: :pray: :pray:

**Comment by Maitreya29** [comment]
pls merge

**Comment by MyHalcyon** [comment]
> pls merge

Pull closed XD

**Review by LinkBoi00 — COMMENTED** [review]
Thanks, it works really well. Now I can run pubg at 120FPS

**Comment by MyHalcyon** [comment]
Lolll

**Comment by Maitreya29** [comment]
Any updates on this useful feature?

**Comment by MyHalcyon** [comment]
> Any updates on this useful feature?

no

**Comment by Maitreya29** [comment]
> > Any updates on this useful feature?
> 
> no

who are you and who asked you

**Comment by MyHalcyon** [comment]
> > > Any updates on this useful feature?
> > 
> > 
> > no
> 
> who are you and who asked you

i am ghost

**Pull request closed without merging**
